services:
  mosquitto:
    build: .
    image: aguasbelas/mosquitto
    container_name: mqtt-broker
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./config:/mosquitto/config:ro
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    healthcheck:
      test: ["CMD", "mosquitto_sub", "-h", "localhost", "-p", "1883", "-t", "\\$$SYS/#", "-C", "1"]
      interval: 30s
      timeout: 10s
      retries: 3